### ISSUE TITLE
Note about `.onLoad`

### ISSUE THREAD

**Issue by flinder** [SMAPPNYU/mediascores#20]
I get the following `NOTE` from `R CMD check`:
```
checking R code for possible problems ... NOTE
  File ‘mediascores/R/zzz.R’:
    .onLoad calls:
      packageStartupMessage("\nmediascores: News-sharing Ideology from Social Media Link Data.\nVersion 0.0.1.9000 (Development Version)\ncopyright (c) 2019, Gregory Eady, New York University\n                    Fridolin Linder, New York University\nFor citation information, type citation(\"mediascores\").\n")
  
  See section ‘Good practice’ in '?.onAttach'.
```
I checked the relevant section in `.onAttach` but can't tell what the problem is. @GregoryEady do you get that note too?

**Comment by GregoryEady** [comment]
From what I can tell, this can simply be ignored. Googling it shows that people just ignore it. We can avoid it by using `cat()`, but this is supposedly bad practice because it prevents users from suppressing the message. I'd just leave it as is.

**Comment by GregoryEady** [comment]
Closing this issue. Can leave as is.

**Comment by flinder** [comment]
ok fine with closing it
