### ISSUE TITLE
error occurred during calling the sampler; sampling not done

### ISSUE THREAD

**Issue by mmosleh** [SMAPPNYU/mediascores#24]
I try to run the sample code and keep receiving the following error. I am using MacOS Catalina

error occurred during calling the sampler; sampling not done

**Comment by GregoryEady** [comment]
To be clear, you're running the following?

```
library(mediascores)
data(MOC115)
fitted_model <- mediascores(Y = MOC115[, 7:151], group = MOC115$group,
                            anchors = c(1, 2),
                            chains = 4, cores = 4,
                            warmup = 750, iter = 1500)
```

I'm on Catalina 10.15.4 (like you I suspect) with R 4.0.0 and the newest release of rstan and that will run for me. So this one might be tough to debug. If you haven't yet, it might be worthwhile to ensure that rstan is the newest version. I know that Stan had a number of problems with the switch to Catalina, but I believe the newest release of rstan corrected those problems.

It might be worthwhile to also try including the argument "variational = TRUE" to see if the variational Bayes version will work.

**Comment by mmosleh** [comment]
Awesome! thank you! seems updating the packages did the job!

I was wondering where I can find the list of domains used by this package so I transform my data accordingly (counts of outlet shares)! 

Thank you!

**Comment by GregoryEady** [comment]
There will be more niche domains in the US context, but the majority of those related to US politics can be seen with the packaged dataset as follows:

colnames(MOC115[, 7:151])

Once there's a finalized version of the R library I'll see about putting out a more complete list of US national news domains.

**Comment by mmosleh** [comment]
Awesome! thank you & looking forward to the new version.

Also is it computationally feasible to do this for 8k users ?

**Comment by GregoryEady** [comment]
Variational will be relatively quick for 8k. Full Bayes on 8k will take some time (a few days I suspect). The code is parallelized so that you can run, say, 4 chains on 20 cores presuming you have access to one. At the end of the vignette, I discuss parallelizing the chains, but it can be a bit finicky to set up.

**Comment by mmosleh** [comment]
Awesome! many thanks!
