### ISSUE TITLE
Alignment of domains

### ISSUE THREAD

**Issue by mmosleh** [SMAPPNYU/mediascores#25]
I understand I can use `colnames(MOC115[, 7:151]) ` to see a list of domains used to the estimation, I was wondering how can see the alignment of these reference domains? (how left or right these domains are assumed,

Thank you!

**Comment by GregoryEady** [comment]
Answered offline, so closing thread. But for anyone interested, one can run the model from the packaged dataset to extract the estimated mediascores for the reference domains. The vignette that explains how to do so can be found here: http://htmlpreview.github.io/?https://github.com/SMAPPNYU/mediascores/blob/master/vignettes/mediascores-vignette.html
