### ISSUE TITLE
Mediascore outputs for media outlets?

### ISSUE THREAD

**Issue by soubhikbarari** [SMAPPNYU/mediascores#27]
Hi SMAPP team,
Big fan of this paper as a fellow polcomm scholar! I was wondering if you might be able to add the media scores for the outlets in your vignette to the data in this repo, in addition to the MCs?

![Screen Shot 2020-07-15 at 8 24 04 PM](https://user-images.githubusercontent.com/5015674/87612743-6309a200-c6d9-11ea-92c0-babcf7780e9f.png)

Unless I missed it and it's already there ... let me know at your convenience!

Cheers,
Soubhik

**Comment by GregoryEady** [comment]
Hi Soubhik,

Yup, you can actually just run the model that's in the vignette and pull out the estimates from the model itself. The plan is to soon(ish) publish estimates of media organizations and MoCs/governors/Trump etc. as a csv. We're just in the last stages of finishing up the paper itself.

**Comment by ck37** [comment]
Hello,

I am also interested in the csv/xls of the media scores, for incorporation into a paper examining hate speech in social media posts. Is it possible to share?

Thanks,
Chris
