### ISSUE TITLE
Stan parallelization as argument to `mediascores`

### ISSUE THREAD

**Issue by flinder** [SMAPPNYU/mediascores#9]

**Comment by GregoryEady** [comment]
I suggest that we add the following argument to the `mediascores()` function:

`threads`: the number of threads to use for estimation (for map-reduce)
`chains`: the number of estimation chains
`iter`:  the number of total iterations per chain
`warmup`:  the number of total iterations for warmup
`refresh`: how often user is total what iteration each chain is on

The latter four arguments are commonly modified Stan argument which I think would be good to make explicit for user in our function.

**Comment by flinder** [comment]
`chains`, `iter` and `warmup` are already implicit arguments bc. they are passed on to to `rstan::sampling` via `...`. 

It's not super transparent to less experienced users, I guess bc they have to got to the stan documentation to figure out the arguments. 

We could add them as explicit keyword arguments and pass more obscure stuff via `...`. I guess the advantage of how it is now is just consistency, so I'm fine either way

**Comment by GregoryEady** [comment]
Yes, the reason would just be to highlight the main arguments that will be used by users who are not familiar with Stan (the vast majority of people I assume). Then the obscure parts could be passed via `...`.

**Comment by flinder** [comment]
sounds good. I'll change it to that then
